chore: add gitflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,19 +67,31 @@ jobs:
       - name: Push Docker Image to Docker Hub
         run: docker push sjnnj/reservation:latest
 
-      # 9. Stop and Remove Existing Container
+  deploy:
+    needs: build
+    name: Deploy
+    runs-on: ubuntu-latest
+    steps:
+      # 1. Docker Login
+      - name: Docker Login
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      # 2. Stop and Remove Existing Container
       - name: Stop and Remove Existing Container
         run: |
           docker ps -q --filter "name=reservation" | xargs -r docker stop
           docker ps -aq --filter "name=reservation" | xargs -r docker rm
 
-      # 10. Remove Old Docker Images
+      # 3. Remove Old Docker Images
       - name: Remove Old Docker Images
         run: |
           docker images -q --filter "dangling=true" | xargs -r docker rmi
-          docker images -q sjnnj/reservation | xargs -r docker rmi
+          docker images -q sjnnj/reservation:latest | xargs -r docker rmi
 
-      # 11. Pull Docker Image with Retry and Logs
+      # 4. Pull Docker Image with Retry and Logs
       - name: Pull Docker Image with Retry
         run: |
           for i in {1..3}; do
@@ -89,20 +101,20 @@ jobs:
           echo "Final Docker Image List:"
           docker images
 
-      # 12. Run Docker Container with Retry
+      # 5. Run Docker Container with Retry
       - name: Run New Docker Container with Retry
         run: |
           for i in {1..3}; do
-            echo "Attempting to run Docker container (try $i)..."
-            docker run -d -p 8080:8080 --name reservation \
-              -e RDS_URL=${{ secrets.RDS_URL }} \
-              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
-              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
-              sjnnj/reservation:latest && break || echo "Run failed. Retrying in 10 seconds..." && sleep 10;
+          echo "Attempting to run Docker container (try $i)..."
+          docker run -d -p 8080:8080 --name reservation \
+          -e RDS_URL=${{ secrets.RDS_URL }} \
+          -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
+          -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
+          sjnnj/reservation:latest && break || echo "Run failed. Retrying in 10 seconds..." && sleep 10;
           done
-
-      # 13. Verify Container is Running
-      - name: Verify Container is Running
-        run: |
-          echo "Verifying that the container is running..."
-          docker ps --filter "name=reservation"
+          
+          # 6. Verify Container is Running
+          - name: Verify Container is Running
+            run: |
+              echo "Verifying that the container is running..."
+              docker ps --filter "name=reservation"
