chore: add gitflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -105,16 +105,16 @@ jobs:
       - name: Run New Docker Container with Retry
         run: |
           for i in {1..3}; do
-          echo "Attempting to run Docker container (try $i)..."
-          docker run -d -p 8080:8080 --name reservation \
-          -e RDS_URL=${{ secrets.RDS_URL }} \
-          -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
-          -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
-          sjnnj/reservation:latest && break || echo "Run failed. Retrying in 10 seconds..." && sleep 10;
+            echo "Attempting to run Docker container (try $i)..."
+            docker run -d -p 8080:8080 --name reservation \
+              -e RDS_URL=${{ secrets.RDS_URL }} \
+              -e RDS_USERNAME=${{ secrets.RDS_USERNAME }} \
+              -e RDS_PASSWORD=${{ secrets.RDS_PASSWORD }} \
+              sjnnj/reservation:latest && break || echo "Run failed. Retrying in 10 seconds..." && sleep 10;
           done
-          
-          # 6. Verify Container is Running
-          - name: Verify Container is Running
-            run: |
-              echo "Verifying that the container is running..."
-              docker ps --filter "name=reservation"
+
+      # 6. Verify Container is Running
+      - name: Verify Container is Running
+        run: |
+          echo "Verifying that the container is running..."
+          docker ps --filter "name=reservation"
