chore: add gitflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -89,7 +89,7 @@ jobs:
       - name: Remove Old Docker Images
         run: |
           docker images -q --filter "dangling=true" | xargs -r docker rmi
-          docker images -q ${{ secrets.DOCKER_USERNAME }}/reservation:latest | xargs -r docker rmi
+          docker images -q sjnnj/reservation:latest | xargs -r docker rmi
 
       # 4. Pull Docker Image with Retry and Logs
       - name: Pull Docker Image with Retry
@@ -101,7 +101,16 @@ jobs:
           echo "Final Docker Image List:"
           docker images
 
-      # 5. Run Docker Container with Retry
+      # 5. Ensure Docker Image Exists Locally
+      - name: Ensure Docker Image Exists
+        run: |
+          echo "Checking if Docker image sjnnj/reservation:latest exists locally..."
+          if ! docker images sjnnj/reservation:latest | grep sjnnj/reservation; then
+            echo "Error: Docker image sjnnj/reservation:latest not found locally.";
+            exit 1;
+          fi
+
+      # 6. Run Docker Container with Retry
       - name: Run New Docker Container with Retry
         run: |
           for i in {1..3}; do
@@ -114,7 +123,7 @@ jobs:
           done
           echo "Container run command completed."
 
-      # 6. Verify Container is Running
+      # 7. Verify Container is Running
       - name: Verify Container is Running
         run: |
           echo "Verifying that the container is running..."
